import type { CartographicThemeConfig, CartographyStyleId, UserStylePreset } from '../../types/cartography';

const CUSTOM_PRESETS_KEY = 'createfantasymap_user_cartography_presets';

export const CARTOGRAPHY_PRESETS: Record<CartographyStyleId, CartographicThemeConfig> = {
  parchment: {
    id: 'parchment',
    name: 'Classic Parchment',
    description: 'Traditional antique cartography style with warm parchment texture tones.',
    terrainColor: '#f4ebd0',
    terrainTexture: 'parchment',
    reliefShadingEnabled: true,
    hillshadeAngle: 315,
    hillshadeStrength: 0.4,
    contourLinesEnabled: false,
    oceanColor: '#c8d6e5',
    coastColor: '#b8c6d5',
    waterPattern: 'parchment',
    coastlineVariant: 'double-line',
    mountainVariant: 'classic-peaks',
    mountainColor: '#7f8c8d',
    forestColor: '#27ae60',
    forestStroke: '#1e8449',
    settlementVariant: 'classic-icon',
    capitalColor: '#d4af37',
    cityColor: '#2c3e50',
    townColor: '#34495e',
    borderVariant: 'solid',
    borderColor: '#d4af37',
    borderWidth: 2,
    roadColor: '#8e44ad',
    roadWidth: 2,
    fontCategory: 'Cinzel',
    textColor: '#2c3e50',
    oceanTextColor: '#2980b9',
    autoCollisionDetection: true,
    labelDensity: 'medium'
  },
  'dark-fantasy': {
    id: 'dark-fantasy',
    name: 'Dark Fantasy',
    description: 'Grim obsidian realms with glowing rune borders and shadow ocean depths.',
    terrainColor: '#171d29',
    terrainTexture: 'noise',
    reliefShadingEnabled: true,
    hillshadeAngle: 315,
    hillshadeStrength: 0.7,
    contourLinesEnabled: true,
    oceanColor: '#0b1325',
    coastColor: '#1e293b',
    waterPattern: 'ink',
    coastlineVariant: 'soft-glow',
    mountainVariant: 'dark-silhouettes',
    mountainColor: '#475569',
    forestColor: '#064e3b',
    forestStroke: '#022c22',
    settlementVariant: 'heraldic-crest',
    capitalColor: '#f59e0b',
    cityColor: '#f8fafc',
    townColor: '#cbd5e1',
    borderVariant: 'glowing-rune',
    borderColor: '#f59e0b',
    borderWidth: 2.5,
    roadColor: '#38bdf8',
    roadWidth: 2,
    fontCategory: 'Cinzel',
    textColor: '#f8fafc',
    oceanTextColor: '#38bdf8',
    autoCollisionDetection: true,
    labelDensity: 'medium'
  },
  'high-fantasy': {
    id: 'high-fantasy',
    name: 'High Fantasy',
    description: 'Rich colorful fantasy atlas with vibrant biomes and gold borders.',
    terrainColor: '#ecfdf5',
    terrainTexture: 'clean',
    reliefShadingEnabled: true,
    hillshadeAngle: 315,
    hillshadeStrength: 0.3,
    contourLinesEnabled: false,
    oceanColor: '#bae6fd',
    coastColor: '#7dd3fc',
    waterPattern: 'flat',
    coastlineVariant: 'double-line',
    mountainVariant: 'classic-peaks',
    mountainColor: '#64748b',
    forestColor: '#10b981',
    forestStroke: '#047857',
    settlementVariant: 'double-ring',
    capitalColor: '#fbbf24',
    cityColor: '#1e293b',
    townColor: '#334155',
    borderVariant: 'solid',
    borderColor: '#f59e0b',
    borderWidth: 2,
    roadColor: '#a855f7',
    roadWidth: 2,
    fontCategory: 'Cinzel',
    textColor: '#0f172a',
    oceanTextColor: '#0284c7',
    autoCollisionDetection: true,
    labelDensity: 'high'
  },
  medieval: {
    id: 'medieval',
    name: 'Medieval Chronicle',
    description: 'Illuminated manuscript style with gothic fonts and hand-inked borders.',
    terrainColor: '#fef3c7',
    terrainTexture: 'aged',
    reliefShadingEnabled: false,
    hillshadeAngle: 315,
    hillshadeStrength: 0.2,
    contourLinesEnabled: true,
    oceanColor: '#e0f2fe',
    coastColor: '#bae6fd',
    waterPattern: 'waves',
    coastlineVariant: 'ink-line',
    mountainVariant: 'ink-hatching',
    mountainColor: '#78350f',
    forestColor: '#15803d',
    forestStroke: '#166534',
    settlementVariant: 'heraldic-crest',
    capitalColor: '#b45309',
    cityColor: '#451a03',
    townColor: '#78350f',
    borderVariant: 'ink-drawn',
    borderColor: '#b45309',
    borderWidth: 2,
    roadColor: '#92400e',
    roadWidth: 1.5,
    fontCategory: 'Medieval',
    textColor: '#451a03',
    oceanTextColor: '#0369a1',
    autoCollisionDetection: true,
    labelDensity: 'medium'
  },
  'hand-drawn': {
    id: 'hand-drawn',
    name: 'Hand Drawn Ink',
    description: 'Sketch-book ink aesthetic with organic stroke line variations.',
    terrainColor: '#fafaf9',
    terrainTexture: 'noise',
    reliefShadingEnabled: true,
    hillshadeAngle: 315,
    hillshadeStrength: 0.5,
    contourLinesEnabled: true,
    oceanColor: '#f1f5f9',
    coastColor: '#e2e8f0',
    waterPattern: 'ink',
    coastlineVariant: 'ink-line',
    mountainVariant: 'ink-hatching',
    mountainColor: '#334155',
    forestColor: '#475569',
    forestStroke: '#1e293b',
    settlementVariant: 'classic-icon',
    capitalColor: '#0f172a',
    cityColor: '#1e293b',
    townColor: '#475569',
    borderVariant: 'ink-drawn',
    borderColor: '#0f172a',
    borderWidth: 2,
    roadColor: '#64748b',
    roadWidth: 1.5,
    fontCategory: 'Georgia',
    textColor: '#0f172a',
    oceanTextColor: '#475569',
    autoCollisionDetection: true,
    labelDensity: 'medium'
  },
  minimal: {
    id: 'minimal',
    name: 'Modern Minimal',
    description: 'Clean high-contrast vector presentation with crisp geometric icons.',
    terrainColor: '#ffffff',
    terrainTexture: 'clean',
    reliefShadingEnabled: false,
    hillshadeAngle: 315,
    hillshadeStrength: 0.0,
    contourLinesEnabled: false,
    oceanColor: '#f8fafc',
    coastColor: '#f1f5f9',
    waterPattern: 'flat',
    coastlineVariant: 'ink-line',
    mountainVariant: 'minimal-triangles',
    mountainColor: '#94a3b8',
    forestColor: '#cbd5e1',
    forestStroke: '#64748b',
    settlementVariant: 'minimal-dot',
    capitalColor: '#0f172a',
    cityColor: '#334155',
    townColor: '#64748b',
    borderVariant: 'dashed',
    borderColor: '#64748b',
    borderWidth: 1.5,
    roadColor: '#94a3b8',
    roadWidth: 1,
    fontCategory: 'Inter',
    textColor: '#0f172a',
    oceanTextColor: '#64748b',
    autoCollisionDetection: true,
    labelDensity: 'low'
  },
  explorer: {
    id: 'explorer',
    name: "Explorer's Map",
    description: 'Expedition field map with coordinate grid markings and compass rose.',
    terrainColor: '#fffbeb',
    terrainTexture: 'aged',
    reliefShadingEnabled: true,
    hillshadeAngle: 315,
    hillshadeStrength: 0.4,
    contourLinesEnabled: true,
    oceanColor: '#f0f9ff',
    coastColor: '#e0f2fe',
    waterPattern: 'parchment',
    coastlineVariant: 'parchment-edge',
    mountainVariant: 'classic-peaks',
    mountainColor: '#92400e',
    forestColor: '#166534',
    forestStroke: '#14532d',
    settlementVariant: 'classic-icon',
    capitalColor: '#b45309',
    cityColor: '#451a03',
    townColor: '#78350f',
    borderVariant: 'dashed',
    borderColor: '#b45309',
    borderWidth: 2,
    roadColor: '#d97706',
    roadWidth: 2,
    fontCategory: 'Cinzel',
    textColor: '#451a03',
    oceanTextColor: '#0369a1',
    autoCollisionDetection: true,
    labelDensity: 'medium'
  },
  ancient: {
    id: 'ancient',
    name: 'Ancient Weathered',
    description: 'Severely aged historical artifact map with faded inks and sepia washes.',
    terrainColor: '#fef3c7',
    terrainTexture: 'aged',
    reliefShadingEnabled: true,
    hillshadeAngle: 315,
    hillshadeStrength: 0.6,
    contourLinesEnabled: true,
    oceanColor: '#fde68a',
    coastColor: '#fcd34d',
    waterPattern: 'parchment',
    coastlineVariant: 'parchment-edge',
    mountainVariant: 'ink-hatching',
    mountainColor: '#78350f',
    forestColor: '#854d0e',
    forestStroke: '#713f12',
    settlementVariant: 'classic-icon',
    capitalColor: '#92400e',
    cityColor: '#451a03',
    townColor: '#78350f',
    borderVariant: 'ink-drawn',
    borderColor: '#78350f',
    borderWidth: 2,
    roadColor: '#b45309',
    roadWidth: 1.5,
    fontCategory: 'Medieval',
    textColor: '#451a03',
    oceanTextColor: '#78350f',
    autoCollisionDetection: true,
    labelDensity: 'low'
  }
};

export const CartographyEngine = {
  getThemeConfig(styleId: CartographyStyleId): CartographicThemeConfig {
    return CARTOGRAPHY_PRESETS[styleId] || CARTOGRAPHY_PRESETS.parchment;
  },

  parseStylePrompt(prompt: string): Partial<CartographicThemeConfig> {
    const text = prompt.toLowerCase();
    if (text.includes('dark') || text.includes('obsidian') || text.includes('grim')) {
      return CARTOGRAPHY_PRESETS['dark-fantasy'];
    }
    if (text.includes('medieval') || text.includes('gothic') || text.includes('manuscript')) {
      return CARTOGRAPHY_PRESETS['medieval'];
    }
    if (text.includes('minimal') || text.includes('clean') || text.includes('modern')) {
      return CARTOGRAPHY_PRESETS['minimal'];
    }
    if (text.includes('hand') || text.includes('ink') || text.includes('sketch')) {
      return CARTOGRAPHY_PRESETS['hand-drawn'];
    }
    return CARTOGRAPHY_PRESETS['parchment'];
  }
};
